### ISSUE TITLE
Can not find the file "LNCaP_RANseq_samples.csv"

### ISSUE THREAD

**Issue by NiklausZZZ** [schoo7/LNCaP-ADT#1]
Hi,

Thank you for your useful tool and data sets. 
I can not find the file "LNCaP_RANseq_samples.csv" in Figshare or Github. I want to ask where can I get this file? The metadata file contains annotation information. 
Many thanks!

**Comment by schoo7** [comment]
Thank you for the comment! I appreciate you like this tool and I am sorry for the late reply. You can find the sample list at Figshare: https://doi.org/10.60688/lsuhs.27179829.v1.
